services:
  tyre_match_backend:
    container_name: backend
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - ${EXPOSE_PORT}:${PORT}
    restart: on-failure
    volumes:
      - ./:/app/
    depends_on:
      - tyre-match-backend-mysql
    env_file:
      - .env
    environment:
      - DB_CONNECTION=${DB_HOST}:${DB_PORT}
      - WAIT_HOSTS=${DB_HOST}:${DB_PORT}
      - WAIT_BEFORE_HOSTS=7
      - WAIT_SLEEP_INTERVAL=3
    networks:
      - tyre-match-backend-stack

  tyre-match-backend-mysql:
    image: mysql:5.7
    platform: linux/x86_64
    container_name: database
    ports:
      - ${EXPOSE_DB_PORT}:${DB_PORT}
    environment:
      - MYSQL_ROOT_HOST=${DB_HOST}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - database_mysql:/var/lib/mysql
    networks:
      - tyre-match-backend-stack

volumes:
  database_mysql:

networks:
  tyre-match-backend-stack:
    driver: bridge