"""Created tyre impression processing table

Revision ID: 3a3a40211772
Revises: f45d3b90fa8e
Create Date: 2026-05-25 10:51:55.684692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a3a40211772'
down_revision = 'f45d3b90fa8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tyre_impression_processing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tyre_impression_id', sa.Integer(), nullable=False),
    sa.Column('grayscale_path', sa.String(length=255), nullable=True),
    sa.Column('binary_path', sa.String(length=255), nullable=True),
    sa.Column('skeleton_path', sa.String(length=255), nullable=True),
    sa.Column('edge_density', sa.Float(), nullable=True),
    sa.Column('void_ratio', sa.Float(), nullable=True),
    sa.Column('groove_count', sa.Integer(), nullable=True),
    sa.Column('preprocessing_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tyre_impression_id'], ['tyre_impressions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tyre_impression_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tyre_impression_processing')
    # ### end Alembic commands ###
