"""Removed defined relationship between tyre impression processing and files

Revision ID: 6044c53dc9d8
Revises: f684e25c5f54
Create Date: 2026-05-27 12:50:06.620063

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6044c53dc9d8'
down_revision = 'f684e25c5f54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tyre_impression_processing', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('tyre_impression_processing_ibfk_4'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('tyre_impression_processing_ibfk_3'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('tyre_impression_processing_ibfk_7'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('tyre_impression_processing_ibfk_5'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('tyre_impression_processing_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('tyre_impression_processing_ibfk_6'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('binary_file_id'))
        batch_op.drop_index(batch_op.f('clean_file_id'))
        batch_op.drop_index(batch_op.f('enhanced_file_id'))
        batch_op.drop_index(batch_op.f('normalised_file_id'))
        batch_op.drop_index(batch_op.f('original_file_id'))
        batch_op.drop_index(batch_op.f('skeleton_file_id'))
        batch_op.drop_column('original_file_id')
        batch_op.drop_column('clean_file_id')
        batch_op.drop_column('skeleton_file_id')
        batch_op.drop_column('normalised_file_id')
        batch_op.drop_column('enhanced_file_id')
        batch_op.drop_column('binary_file_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tyre_impression_processing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('binary_file_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('enhanced_file_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('normalised_file_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('skeleton_file_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('clean_file_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('original_file_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('skeleton_file_id'), ['skeleton_file_id'], unique=True)
        batch_op.create_index(batch_op.f('original_file_id'), ['original_file_id'], unique=True)
        batch_op.create_index(batch_op.f('normalised_file_id'), ['normalised_file_id'], unique=True)
        batch_op.create_index(batch_op.f('enhanced_file_id'), ['enhanced_file_id'], unique=True)
        batch_op.create_index(batch_op.f('clean_file_id'), ['clean_file_id'], unique=True)
        batch_op.create_index(batch_op.f('binary_file_id'), ['binary_file_id'], unique=True)
        batch_op.create_foreign_key(batch_op.f('tyre_impression_processing_ibfk_6'), 'files', ['enhanced_file_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('tyre_impression_processing_ibfk_2'), 'files', ['binary_file_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('tyre_impression_processing_ibfk_5'), 'files', ['normalised_file_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('tyre_impression_processing_ibfk_7'), 'files', ['skeleton_file_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('tyre_impression_processing_ibfk_3'), 'files', ['clean_file_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('tyre_impression_processing_ibfk_4'), 'files', ['original_file_id'], ['id'])

    # ### end Alembic commands ###
