"""Created tyre_models table

Revision ID: a06873882603
Revises: 
Create Date: 2026-05-19 14:38:36.799701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a06873882603'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tyre_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(length=100), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('vehicle_type', sa.String(length=50), nullable=True),
    sa.Column('width_mm', sa.Integer(), nullable=True),
    sa.Column('aspect_ratio', sa.Integer(), nullable=True),
    sa.Column('rim_diameter_inches', sa.Integer(), nullable=True),
    sa.Column('groove_count', sa.Integer(), nullable=True),
    sa.Column('pattern_type', sa.String(length=50), nullable=True),
    sa.Column('tread_pitch_length_mm', sa.Float(), nullable=True),
    sa.Column('dataset_source', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tyre_models')
    # ### end Alembic commands ###
