"""Created files table and updated tyre impression models to reflect

Revision ID: f684e25c5f54
Revises: bc09c644c37b
Create Date: 2026-05-26 20:14:47.399387

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f684e25c5f54'
down_revision = 'bc09c644c37b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.Enum('tyre_model', 'tyre_impression', name='filemodel'), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.Enum('original', 'normalised', 'enhanced', 'binary', 'clean', 'skeleton', name='filetype'), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_location', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.create_index('index_file_owner', ['model', 'model_id'], unique=False)

    with op.batch_alter_table('tyre_impression_processing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_file_id', sa.Integer(), unique=True, nullable=True))
        batch_op.add_column(sa.Column('normalised_file_id', sa.Integer(), unique=True, nullable=True))
        batch_op.add_column(sa.Column('enhanced_file_id', sa.Integer(), unique=True, nullable=True))
        batch_op.add_column(sa.Column('binary_file_id', sa.Integer(), unique=True, nullable=True))
        batch_op.add_column(sa.Column('clean_file_id', sa.Integer(), unique=True, nullable=True))
        batch_op.add_column(sa.Column('skeleton_file_id', sa.Integer(), unique=True, nullable=True))
        batch_op.create_foreign_key(None, 'files', ['binary_file_id'], ['id'])
        batch_op.create_foreign_key(None, 'files', ['clean_file_id'], ['id'])
        batch_op.create_foreign_key(None, 'files', ['original_file_id'], ['id'])
        batch_op.create_foreign_key(None, 'files', ['normalised_file_id'], ['id'])
        batch_op.create_foreign_key(None, 'files', ['enhanced_file_id'], ['id'])
        batch_op.create_foreign_key(None, 'files', ['skeleton_file_id'], ['id'])
        batch_op.drop_column('skeleton_path')
        batch_op.drop_column('normalised_path')
        batch_op.drop_column('enhanced_path')
        batch_op.drop_column('clean_path')
        batch_op.drop_column('binary_path')

    with op.batch_alter_table('tyre_impressions', schema=None) as batch_op:
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tyre_impressions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', mysql.VARCHAR(length=255), nullable=False))

    with op.batch_alter_table('tyre_impression_processing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('binary_path', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('clean_path', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('enhanced_path', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('normalised_path', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('skeleton_path', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('skeleton_file_id')
        batch_op.drop_column('clean_file_id')
        batch_op.drop_column('binary_file_id')
        batch_op.drop_column('enhanced_file_id')
        batch_op.drop_column('normalised_file_id')
        batch_op.drop_column('original_file_id')

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_index('index_file_owner')

    op.drop_table('files')
    # ### end Alembic commands ###
