  name: TyreMatch API CI

  on:
    push:
      branches:
        - main
    pull_request:
      branches: [main]
    workflow_dispatch:

  jobs:
    build-and-test:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up Go
          uses: actions/setup-go@v5
          with:
            go-version: '1.25.0'
            cache: true

        - name: Create .env file
          run: cp .env.dist .env

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Build docker compose stack
          run: docker compose up --build -d

        - name: Start test database
          run: docker compose -f ./docker-compose-test.yml up --build -d

        - name: Cache OpenCV
          id: opencv-cache
          uses: actions/cache@v4
          with:
            path: ./opencv-install
            key: ${{ runner.os }}-opencv-4.13.0

        - name: Install OpenCV
          uses: rayandrews/with-opencv-action@v1
          with:
            dir: ./opencv-install
            cached: ${{ steps.opencv-cache.outputs.cache-hit }}
            opencv-version: '4.13.0'

        - name: Run tests
          run: go test ./tests

        - name: Tear down test database
          if: always()
          run: docker compose -f ./docker-compose-test.yml down -v

        - name: Tear down api
          if: always()
          run: docker compose down -v
